version: '3'

includes:
  common: ./taskfiles/common.yml
  deps: ./taskfiles/deps.yml
  generate: ./taskfiles/generate.yml
  dev: 
    taskfile: ./taskfiles/dev.yml
    flatten: true

dotenv: ['.env.local']

vars:
  LOCAL_BIN: '{{.PWD}}/bin'
